s = 'sudeepsubhashchandrasupriyabanaganpatsnehamelekarqweqweiqeoiqwoepiqoeqoweoqiwaskdjsdkfljsdklfjnvmxbcvnxcnmvbsdhdjfjsdhdfiquieuqiwriouqrpkflsdlkfjskdfklsdjfklsdjfsdjfkjsdkjfskdjfsdjkfklsjdkfljqiwuqweuqwizxmasdjasdkjaskljdkj'
print s[::-1]
